### ISSUE TITLE
Padronizar nomes e id

### ISSUE THREAD

**Issue by DChrispim** [tvinente/rede-alimenta#31]
Padronizar id e name de elementos que vão receber JavaScript (ex. button, form, input, etc.). Exemplo de padronização
`id="endereco-coleta" name="enderecoColeta"`

**Comment by tvinente** [comment]
* Padronização realizada, conforme alinhamento.
* Manter para os próximos códigos o padrão:
id="endereco-coleta" name="enderecoColeta" class="sample-header"
